services:
  - type: web
    name: trackappointments-backend
    env: python
    plan: standard
    region: oregon
    repo: https://github.com/c50bossio/trackappointments-attribution-tracker.git
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: HASH_SALT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trackappointments-db
          property: connectionString

  - type: web
    name: trackappointments-frontend
    env: node
    plan: standard
    region: oregon
    repo: https://github.com/c50bossio/trackappointments-attribution-tracker.git
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.trackappointments.com

databases:
  - name: trackappointments-db
    databaseName: trackappointments
    plan: basic-1gb