# ConfigMap for BookingBridge Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: bookingbridge-config
  namespace: bookingbridge
  labels:
    app.kubernetes.io/name: bookingbridge
    app.kubernetes.io/component: config
data:
  # Backend Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "https://bookingbridge.com,https://www.bookingbridge.com"
  
  # Database Configuration
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "30"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  
  # Redis Configuration
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "50"
  
  # Celery Configuration
  CELERY_WORKER_CONCURRENCY: "4"
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_ACCEPT_CONTENT: "json"
  
  # Attribution Configuration
  ATTRIBUTION_WINDOW_DAYS: "30"
  MAX_ATTRIBUTION_CONFIDENCE: "100"
  MIN_ATTRIBUTION_CONFIDENCE: "50"
  
  # Security Configuration
  JWT_ALGORITHM: "RS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "30"
  PASSWORD_MIN_LENGTH: "8"
  ACCOUNT_LOCKOUT_THRESHOLD: "5"
  ACCOUNT_LOCKOUT_DURATION_MINUTES: "30"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS_PER_MINUTE: "60"
  RATE_LIMIT_BURST: "10"
  
  # Frontend Configuration
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
---
# Nginx ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: bookingbridge
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: proxy
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    worker_rlimit_nofile 65535;
    
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 4096;
        use epoll;
        multi_accept on;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'rt=$request_time uct="$upstream_connect_time" '
                        'uht="$upstream_header_time" urt="$upstream_response_time"';
        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 30;
        client_max_body_size 10m;
        
        gzip on;
        gzip_vary on;
        gzip_min_length 1000;
        gzip_comp_level 6;
        gzip_types
            application/javascript
            application/json
            application/xml
            text/css
            text/javascript
            text/plain
            text/xml;
        
        upstream backend {
            server bookingbridge-backend:8000;
        }
        
        upstream frontend {
            server bookingbridge-frontend:3000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /api/ {
                proxy_pass http://backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }