# Kubernetes Namespace for BookingBridge
apiVersion: v1
kind: Namespace
metadata:
  name: bookingbridge
  labels:
    app.kubernetes.io/name: bookingbridge
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: attribution-tracker
    app.kubernetes.io/managed-by: kubectl
    environment: production
---
# Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bookingbridge-quota
  namespace: bookingbridge
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "30"
    configmaps: "30"
---
# Network Policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bookingbridge-network-policy
  namespace: bookingbridge
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: attribution-tracker
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: attribution-tracker
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80